# Site settings
title: Linuxdroid
description: > # this means to ignore newlines until "baseurl:"
  Help page for Linuxdroid - terminal emulator and Linux environment for Android.
baseurl: ""
url: "https://linuxdroid.app"

# Build settings
markdown: kramdown
